stages:
- name: build nginx
  steps:
  - publishImageConfig:
      dockerfilePath: ./docker/nginx-proxy/Dockerfile
      buildContext: .
      tag: duginginx:latest
      registry: 127.0.0.1:34724
timeout: 60
